const Map<String, String> en = {
  'Username': 'Username',
  'Password': 'Password',
  'Sign In': 'Sign In',
  'This field is required': 'This field is required',
  'Something went wrong': 'Something went wrong',
  'Incorrect username or password': 'Incorrect username or password',
  'Please try again': 'Please try again',
  'Loading ...': 'Loading ...',
  'Take Away': 'Take Away',
  'Dine In': 'Dine In',
  'Time Card': 'Time Card',
  'Pay In': 'Pay In',
  'Pay Out': 'Pay Out',
  'Cash In': 'Cash In',
  'Cash Out': 'Cash Out',
  'Refund': 'Refund',
  'Safe Mode': 'Safe Mode',
  'Cash Drawer': 'Cash Drawer',
  'Branch': 'Branch',
  'Exit': 'Exit',
  'Manual': 'Manual',
  'Money Count': 'Money Count',
  'Qty': 'Qty',
  'Total': 'Total',
  'Cash': 'Cash',
  'Save': 'Save',
  'Voucher Number': 'Voucher Number',
  'POS No': 'POS No',
  'Original Data': 'Original Data',
  'Original Time': 'Original Time',
  'Table No': 'Table No',
  'Customer': 'Customer',
  'Show': 'Show',
  'Discount': 'Discount',
  'Net Total': 'Net Total',
  'Ok': 'Ok',
  'Serial': 'Serial',
  'Item': 'Item',
  'R.Qty': 'R.Qty',
  'R.Total': 'R.Total',
  'Quantity must be greater than or equal to': 'Quantity must be greater than or equal to',
  'Quantity must be less than or equal to': 'Quantity must be less than or equal to',
  'Vh No': 'Vh No',
  'Table': 'Table',
  'Check': 'Check',
  'Modifier': 'Modifier',
  'Void': 'Void',
  'Delivery': 'Delivery',
  'Line Discount': 'Line Discount',
  'Split': 'Split',
  'Price Change': 'Price Change',
  'Pro-Nam': 'Pro-Nam',
  'Sub Total': 'Sub Total',
  'Price': 'Price',
  'Service': 'Service',
  'Tax': 'Tax',
  'Pay': 'Pay',
  'Order': 'Order',
  'Amount Due': 'Amount Due',
  'Delivery Charge': 'Delivery Charge',
  'Employee Id': 'Employee Id',
  'Search': 'Search',
  'Please select the item you want to remove': 'Please select the item you want to remove',
  'Are you sure to remove the': 'Are you sure to remove the',
  'item': 'item',
  'Cancel': 'Cancel',
  'Confirm': 'Confirm',
  'Please select the item you want to modifier': 'Please select the item you want to modifier',
  'Please select the item you want to line discount': 'Please select the item you want to line discount',
  'Please select the item you want to price change': 'Please select the item you want to price change',
  'Line discount is not available for this item': 'Line discount is not available for this item',
  'Price change is not available for this item': 'Price change is not available for this item',
  'No items accept discount in order': 'No items accept discount in order',
  'Percentage': 'Percentage',
};
