const Map<String, String> en = {
  'Username':'Username',
  'Password':'Password',
  'Sign In':'Sign In',
  'This field is required':'This field is required',
  'Something went wrong':'Something went wrong',
  'Incorrect username or password':'Incorrect username or password',
  'Please try again':'Please try again',
  'Loading ...':'Loading ...',
  'Take Away':'Take Away',
  'Dine In':'Dine In',
  'Time Card':'Time Card',
  'Pay In':'Pay In',
  'Pay Out':'Pay Out',
  'Refund':'Refund',
  'Safe Mode':'Safe Mode',
  'Cash Drawer':'Cash Drawer',
  'Branch':'Branch',
  'Exit':'Exit',
  'Manual':'Manual',
  'Money Count':'Money Count',
  'Qty':'Qty',
  'Total':'Total',
  'Cash':'Cash',
  'Save':'Save',
};